### ISSUE TITLE
Music Enthusiest

### ISSUE THREAD

**Issue by Kclaster** [Kclaster/teamAwsome#2]
### Story
As a music enthusiast, I want to create a Spotify playlists based on my favorite movie genres, so that I experience the nostalgia of the movie while away from the screen.

### Acceptance Criteria
- [ ]  Create an input field for omdb genre
- [ ] Create list movies from omdb AJAX GET
- [ ] Display list on screen with images
- [ ] Add button under each movie to quickly add songs to your Spotify movie playlist.
